### PR TITLE
Add new List of Terms document to Darwin Core landing page

### PR DESCRIPTION
**Pull request by baskaufs**
This will complete checkbox 4 of https://github.com/tdwg/dwc/issues/265

### CODE REVIEW

**Comment by baskaufs** [comment]
Hmm. I can't seem to suggest reviewers for this. @peterdesmet knows what is going on with this.

**Comment by baskaufs** [comment]
I think it would be a good idea. I didn't make that edit because I was trying to minimize the changes. @tucotuco if you think it is a good idea and @peterdesmet agrees, I'll add some text. Similarly, the list of terms document doesn't mention the QRG, but probably should.

**Comment by tucotuco** [comment]
Yes, I think it is a good idea.

**Comment by baskaufs** [comment]
How about this text about and link to the QRG: https://github.com/tdwg/website/pull/165/commits/e535e8c2ca274adf766915e3c76fb4e351ab50a5 ?

**Comment by stanblum** [comment]
Simple and useful additions to the standard (sensu lato)

**Pull request merged**
