### PR TITLE
Update SDD links

### PR DESCRIPTION
**Pull request by MattBlissett**
Part of https://github.com/tdwg/sdd/issues/11

### CODE REVIEW

**Comment by stanblum** [comment]
Thanks Matt!   I'm still not clear on where all the redirects get made.  One of these days I'll have someone sit down with me and map it out.

**Review by stanblum — APPROVED** [review]

**Comment by baskaufs** [comment]
@stanblum The redirect mechanism depends on the subdomain. Since the "permanent URLs" for standards are in the www.tdwg.org subdomain, their redirects are controlled here
https://github.com/tdwg/infrastructure/blob/master/httpd/www.tdwg.org.conf

The rs.tdwg.org redirects handled by a different server that gets its information from the rs.tdwg.org repository. Redirection is handled differently depending on whether the URL is for a document or for something else. 
- documents: controlled by the `browserRedirectUri`column of https://github.com/tdwg/rs.tdwg.org/blob/master/docs/docs.csv
- terms: controlled by https://github.com/tdwg/rs.tdwg.org/blob/master/html/redirects.csv

The redirect for the sdd document needs to be changed in right place. Just changing the hyperlink on the standards landing page is a band-aid. Do you want me to change it?

**Comment by baskaufs** [comment]
That is a great question. For the terms redirects, I know that it happens as soon as the file is updated. I'll have to check on the docs. I think it may require a new release of the rs.tdwg.org repo to be active (but no script running). I think in both cases the cache may need to be flushed since the Nginx front end caches a lot of stuff. 

For reference, all of the details of the update process are here:

https://github.com/tdwg/rs.tdwg.org/blob/master/process/process-vocabulary.md

This is the directory where all of the updating scripts are kept and the CSVs for changed terms. This is a long and complicated process that I'm trying to streamline by including more of the manual steps in scripts. But this is the place to go to make all of the pieces work.

**Comment by baskaufs** [comment]
One quick question while I'm updating the document metadata. I see that currently the `license_statement` has the value "License not asserted". However, by building the page using the TDWG website template, there is now a footer that asserts a CC BY license. 

Can we just do that? I suppose we can get away with that since if there wasn't any license before I suppose it might have been "all rights reserved" by default. So we would be releasing it now under a more permissive license, which I guess is OK.

**Comment by stanblum** [comment]
The website is CC- By, but my understanding is that TDWG standards should be CC-0; attribution is not required.

**Comment by baskaufs** [comment]
Hmm. Perhaps this is something that needs to be clarified. You can see what licenses are listed for all of the standards documents (as opposed to the abstract vocabularies whose data are probably CC0) in the license_statement column of https://github.com/tdwg/rs.tdwg.org/blob/master/docs/docs.csv . As you can see the older ones are all over the map, although most of the newer ones are CC BY. The values listed there are the "facts on the ground" at the time when I created this table. In many cases, the documents as they are now viewable may say CC BY because of the footer template.

**Comment by stanblum** [comment]
Yeah, that's a problem -- incorrect statement of license for the document
because the website template includes that CC-By assertion.

**Comment by baskaufs** [comment]
Alright, it's updated and the redirect is working. FYI, I did have to create a new release for the document redirect to be active and I also flushed the cache since I think there's a pretty long expiration (like 30 days).

**Pull request merged**
