### PR TITLE
added spaces to create new line

### PR DESCRIPTION
**Pull request by debpaul**

### CODE REVIEW

**Review by gkampmeier — APPROVED** [review]
Adding spaces to create a line break does not sound like a best practice.  I see the problem, I will be interested to see if it actually works (and why).

**Comment by gkampmeier** [comment]
Does not appear to have worked, but it's not clear why it is acting this way.

**Comment by stanblum** [comment]
Requiring two spaces at the end of a line to create a line-break might not be part of GitHub markdown (so might not show up in preview), but it apparently is part of the Pelican processing that renders our website.

**Comment by gkampmeier** [comment]
But it didn't work (adding two spaces) and in fact, you couldn't tell that it had done so.  I went back to look after I approved @debpaul use of this trick.  At any rate, it is now fixed.  Thanks!

**Comment by stanblum** [comment]
Well, the pull request wasn't merged when I got to it (and I also checked
the web page to confirm the problem was there).  I did the merge and the
rendering was corrected.  So, I think it did work.  What had not happened
was the merge and subsequent rebuild.

**Comment by debpaul** [comment]
@gkampmeier @stanblum 
Adding two spaces at the end of a line to make a line break is markdown syntax
See https://gist.github.com/shaunlebron/746476e6e7a4d698b373

**Comment by gkampmeier** [comment]
Guess this could have been my fault, not merging properly.  <sigh> Someday this will become second nature.  Thanks @stanblum and @debpaul 

> Well, the pull request wasn't merged when I got to it (and I also checked the web page to confirm the problem was there). I did the merge and the rendering was corrected. So, I think it did work. What had not happened was the merge and subsequent rebuild.

**Pull request merged**
