### PR TITLE
improve docs

### PR DESCRIPTION
**Pull request by vipulsharma001**

### CODE REVIEW

**Review by stanblum — COMMENTED** [review]
Thank you for the compliment, but we will leave it to the viewer/reader to decide whether this project (organization?) is amazing or not.  Our style is to be dispassionate and keep the website as free of subjective  opinions as we can.

**Comment by peterdesmet** [comment]
Hi @stanblum I got a similar unsolicited PR today, from different account. If this continues, we can report the user.

**Comment by stanblum** [comment]
Hmm,  people are attempting to boost on GitHub, trying to raise profile?
Very odd.  Thanks for the heads up!

**Comment by peterdesmet** [comment]
@stanblum I contacted GitHub and it seems this is related to Hacktoberfest, which encourages people to contribute to open source projects (which is great). The kind of pull requests we are seeing however are obviously spam to artificially increase one's contributions. The hacktoberfest guide recommends to just label these as `invalid` and close them: https://hacktoberfest.digitalocean.com/details#quality

So, let's just do that when we encounter more. I've already labeled the two we received.

**Pull request closed without merging**
