### PR TITLE
Organize standards

### PR DESCRIPTION
**Pull request by peterdesmet**
Implement #533

## [Proposal 2](https://github.com/tdwg/website/issues/533#issue-2052440690)

> Proposal 2 is partially implemented in that the page for standards not maintained by TDWG has been created: https://www.tdwg.org/standards/externally-managed/. However, it is not yet linked anywhere.

I have renamed this page to `standards/externally-managed` to `standards/external`. And as I mentioned [here](https://github.com/tdwg/website/issues/533#issuecomment-2076627047), I changed "managed" to "maintained" in the text (there were only a few occurrences)

> The proposal was to change "Standards" at the top of the TDWG website from a link to a dropdown menu. The menu should have one item for the current standards page https://www.tdwg.org/standards/, probably with the label "Current standards", and an additional menu item linking to the new page, probably labeled "Externally managed standards".

This is now done, the dropdown menu items are called:

- `Maintained by TDWG` -> `/standards/`
- `Externally maintained` -> `/standards/external/`

> If at some point in the future standards were retired, we would add a third item for the page of retired standards described in Proposal 1. I think there should also be a regular hyperlink on the current standards page to the externally managed page.

The Standard pages has a bottom section called "Externally maintained" that links to that page

## [Proposal 3](https://github.com/tdwg/website/issues/533#issue-2052440690)

> Proposal 3 involves separating the standards on the current standards page into two lists: "Actively maintained" (at the top of the page), and "Not under active maintenance" (at the bottom of the page).

This is now done. I kept with this proposal and did not create a `/standards/not-maintained/` page as I suggested [here](https://github.com/tdwg/website/issues/533#issuecomment-2076627047). The advantage is that all TDWG standards (maintained or not) are now visible on one page.

> The actively maintained list should include Darwin Core, Audiovisual Core, TAPIR, the SDS, the VMS, the GUID/LSID AS, ABCD, TCS, and the WGSRPD.

Done

> The not under active maintenance list should include Economic Botany Data Collection Standard, Floristic Regions of the World, HISPID3, ITF2, POSS, SDD and XDF. The following standards should be removed from the current standards page since they are now on the page of externally managed standards: Authors of Plant Names, BPH, BPH Supplementum, DELTA, Index Herbariorum, and TL-2. I think this covers all of them but we can double-check this against the proposal to make sure.

The one that was not listed was "Plant Names in Botanical Databases", which I listed under "Not under active maintenance"

## Structure

The standards typically have very long official titles that clutter up the sidebar. So I opted to use acronyms or shorter names  for the headings (and thus sidebar) and the full name to link to the landing page. These acronyms might be less welcoming to newcomers, but it vastly improves readability. I also updated the externally-maintained standard following the same format:

```
### Short title

[Full title](/standards/name/)

or

### Short title

[Full title](/standards/name/) maintained by [x](url).
```

I think in the future, the sections for each standard should be updated to have a short description (which can be taken from or reused as the `description` for the landing page.

## Standards

Standards-TDWG

## Externally-maintained standards

Externally-maintained-standards-TDWG

### CODE REVIEW

**Comment by gkampmeier** [comment]
@peterdesmet this is a huge improvement (and thanks to everyone contributing to this on the TAG) and I agree that while it would make the page longer, it would help users tremendously to have a very short description for (at least) each actively maintained standard. This might argue, because of length of the page, to put the Not under active maintenance group on its own page as is the Externally maintained group.

**Comment by peterdesmet** [comment]
> This might argue, because of length of the page, to put the Not under active maintenance group on its own page as is the Externally maintained group.

Yeah, that was my original idea too (and has some advantages). Should I do this as part of this PR or wait?

**Comment by gkampmeier** [comment]
> Yeah, that was my original idea too (and has some advantages). Should I do this as part of this PR or wait?

I would vote yes. For the future, we have a number of standards or extensions to standards coming online that will need to be referenced so that people can find them. With luck the active standards should only be getting longer ;)

**Comment by stanblum** [comment]
I'm really sorry to go so quiet on this issue.  Several excuses are relevant, the conference prep being the main one.  

In any case, you asked me a draft what we would like the page to look like.  After thinking about it, I came up with [this](https://docs.google.com/document/d/1oKH6cFxpSSYK1nyf2INNAhB1-v6I-krvzcEbJqLuox4/edit?usp=sharing), which is a listing my subject instead of alphabetical by name.  I showed that to Ely and she said OK to propose it to the rest of the Exec.

In the meantime, I'm going to go ahead and merge this.

**Review by baskaufs — APPROVED** [review]
Thanks @peterdesmet for your work on this. It looks marvelous and I think the actions you took were all appropriate.

With respect to moving the non-actively maintained standards to another page, I think that is a good idea, particularly if we do as @gkampmeier suggested and add a short description. When the original proposal was made, it was intended to be somewhat conservative and sensitive to concerns that we don't consider the non-actively maintained standards as "second class". They may be entirely relevant and usable even if they don't need active maintenance. The division was really intended to indicate to people who might want to contribute to the development process whether they should expect there to be a group that they could join to participate in the development. Having said that, as a practical matter, it would be less cluttered to put them on a separate page as long as it is linked and put in the dropdown as was the case for the externally managed ones. So I am in favor of making that change if others don't have an issue (i.e. the concern about people thinking they were "second class"). 

I can see the appeal to the organization that @stanblum suggested. However, it seems like an orthogonal approach to the one we are implementing, and I can't see a way to implement them both simultaneously on the main standards landing page. However, perhaps a good option would be to just create a 3rd (or 4th if we split the main one) page that lists (and links to) them as Stan suggested. That could be added to the menu as "Standards by category" or something like that.

I have another comment about adding the descriptions, but I think that should be discussed as a separate issue from this pull request review.

**Comment by baskaufs** [comment]
@gkampmeier @peterdesmet @stanblum Refer to the issue I created at https://github.com/tdwg/website/issues/547 re: short descriptions of each standard.

**Pull request merged**
