### PR TITLE
Create index.md

### PR DESCRIPTION
**Pull request by qgroom**
News item for the 30-day public review of the ChronometricAge Extension to Darwin Core

### CODE REVIEW

**Review by stanblum — COMMENTED** [review]
Hi Quentin,   This call for public review sounds very formal (like it's part of the ratification process), but it's "out of order".  The TDWG process specifies that expert review happen before the formal 30 day public review.  As far as I know, this has not been submitted to the Exec as a proposed standard and no review manager has been appointed.  We discussed this in the West group call, and someone (James I think; I'll confirm that with him Wed) will get back to John and ask that we modify this call -- make it more of an invitation for anyone interested to have a look and comment / contribute.  The formal ratification process needs to begin with the convener of the IG submitting the proposal through you to the Exec, then the Exec appoints the review manager who engages experts to review it.  Ideally, the proposal could be a MS submitted to BISS.

**Comment by pzermoglio** [comment]
@stanblum I'm sure John will give you all more details about this, but briefly: this is not a new standard, so it would not need a review manager appointed. It is presented as an extension to Darwin Core, and as such, it should be treated as any change to Darwin Core (e.g., adding new terms, updating existing) would, and ruled under its Maintenance Interest Group. It's a similar case to the recent changes for the invasive species-related terms, only this one is a bigger package and organized as an extension.
Hope this helps?

**Comment by tucotuco** [comment]
This is indeed a formal review following section "3.3.2 Public comment" of the [Vocabulary Maintenance Specification](https://github.com/tdwg/vocab/blob/master/vms/maintenance-specification.md) for a vocabulary enhancement. It is not a new standard, it is a Vocabulary Enhancement, see section 4, specifically:

`Because a vocabulary enhancement is special category of vocabulary change, the general change process described in the subsections of Section 3 apply. That is, the vocabulary enhancement as a package will be proposed formally via the tracking system (Section 3.3.1), be subjected to public comment (Section 3.3.2), and forwarded for an Executive Committee Decision (Section 3.3.3) before it is adopted as an addition to the standard.`

Thus, the order is correct and there is no review manager involved - that role is undertaken by the Maintenance Group. In this case official authorization to present for public comment was solicited from the core members of both the DwC Maintenance and ESP Interest Groups, with unanimous approval from both. I believe we are perfectly in keeping with process.

**Comment by tucotuco** [comment]
Perhaps this is the point of confusion, in the Task Group strategy it states 
`The outputs will follow the TDWG Standards Documentation Standard (SDS) and will be reviewed as required processes by the TDWG by-laws https://www.tdwg.org/about/process/ for the ratification of standards.`

During execution of the listed tasks it was clear that the VMS was the relevant document to adhere to.

**Comment by stanblum** [comment]
OK, I misunderstood that.  I thought Chrono would be a separate standard --  it has its own GitHub repo, I had assumed it would have a different standard number, etc. -- as I think other standards that have been called "extensions" have been handled.  My mistake.  (We have woven a tangled web.)  But perhaps also relevant to the concept of a standard's identity, isn't http://rs.tdwg.org/chrono/terms/   a different namespace than  http://rs.tdwg.org/dwc/terms/ or http://rs.tdwg.org/dwc/iri/ (which are obviously hierarchical siblings under dwc)?  

Given my misunderstanding, I'm OK with posting this as is, but I actually don't have any authority on the Exec so I'm going to touch base with others who discussed this in the West Group meeting yesterday.  I expect they'll approve and then I'll merge the commit.

**Comment by tucotuco** [comment]
My stance is that namespace is a matter of convenience. It certainly isn't
a measure of standard identity. DwC and AC include terms from multiple
namespaces already, for example.

**Review by stanblum — APPROVED** [review]
Exec West Group accepts that this can be treated as maintenance of an existing standard by the addition of terms, using the VMS process.

**Pull request merged**
