### PR TITLE
Update chair's affiliation

### PR DESCRIPTION
**Pull request by dkoureas**

### CODE REVIEW

**Comment by peterdesmet** [comment]
@dkoureas Thanks for updating and testing!

**Comment by peterdesmet** [comment]
Now live on website: https://dev.tdwg.org/about/committees/

**Comment by dkoureas** [comment]
@peterdesmet is this the basic workflow you expect us to follow for updating content?

**Comment by peterdesmet** [comment]
@dkoureas yes, this is the procedure for anyone to update the site. A limited group of editors will have direct write access, which does not require creating a branch/fork and a pull request.

**Comment by stanblum** [comment]
I also updated Dimitris's affiliation on the main website (www.tdwg.org).
And our Oceania rep for 2018 on the dev website.

**Pull request merged**
