### PR TITLE
replace backslash newlines with explicit <br/> tags

### PR DESCRIPTION
**Pull request by baskaufs**
@stanblum, the method I was using to generate newlines by ending lines with backslashes apparently isn't supported by our website template. That was causing the Documents sections of the pages look weird. So I regenerated all of the pages to explicitly add break tags at the end of the lines instead. I think that should fix the problem.

### CODE REVIEW

**Review by stanblum — APPROVED** [review]

**Comment by baskaufs** [comment]
Thanks, @stanblum! The pages seem to be rendering correctly now. There will undoubtedly be some broken links, etc. but they can be fixed as they are discovered.

**Comment by stanblum** [comment]
Hey Steve,

I don't think you needed to use the line break element in all those places;
but just what works, or doesn't, is one of the frustrating things about
formatting with this website.  And it's definitely not easy to do if you
don't have write permission so you can experiment easily.  I see what I can
do to clean up formatting here and there, as time permits.

There are a couple standard pages (e.g., Botanico-Periodicum-Huntianum)
where the whole header section has been replicated in the *page's header*,
rather than just the abstract (i.e., summary).  I'm guessing that wasn't
intentional.  Let me know if it was, and why that formatting was used on
some pages but not others.  I'll work on straightening that out later
today.  I'm sure you have enough to do.

-Stan

**Comment by baskaufs** [comment]
Hi Stan,

With respect to the line break issue, without them it was just cramming them all into a single paragraph. There probably would be an alternative way to style that part, but I considered the document metadata to be a pretty vanilla part of the page, so I just put breaks at the ends of the lines.

If you compare the unstyled versions of [a page that works](https://github.com/baskaufs/website/blob/master/content/pages/standards/plant-names-authors/index.md) and [a page that doesn't work](https://github.com/baskaufs/website/blob/master/content/pages/standards/bph/index.md), the difference appears to be that the pages that render incorrectly are missing header data. I'm not sure which of the data are critical, but it's probably the summary field -- I looked at several of the ones that rendered badly and they are all missing that. 

The quick and dirty fix would be to just copy the existing abstract and paste it into the summary field. If someone were motivated later to write a better summary, it could be substituted. Do you want me to try that? It would be pretty quick and easy.

**Comment by stanblum** [comment]
I understand that the lines should have just merged into a big paragraph. I
just meant that I've been able to get lists to format correctly without
resorting to the HTML tags.  No worries.

Regarding the missing metadata for web pages, I think we need to put at
least the basic stuff in there so that the Pelican doesn't get confused or
complain.  As I said, I think you have enough to do, so I'll whittle away
at it (copying the abstract, or some of it, into the summary field.)  I
just wanted to be sure it wasn't intentional.

Thanks,

-stan

**Comment by stanblum** [comment]
oops, I meant "the lines should NOT have just merged into a big paragraph."

**Comment by baskaufs** [comment]
Supposedly you can terminate lines with two trailing spaces, but that leaves you with nothing to actually see when you look at the file, so I decided to just stick in the tags. They are not visible in the end and since I was scripting it anyway, no more work. But if you think it would be easier to maintain the pages without them, I could switch to the two spaces method and re-run the script.

I was thinking that since the old standards are unlikely to change much, after doing the initial setup by script we could just maintain by hand. Under that scenario, it would make sense for you to just fix them by copy and paste. The only reason to continue to update the pages by script would be to keep the actual metadata about the standards and documents in synch with what's being served in the machine-readable metadata. Compare http://rs.tdwg.org/itfbgpr/doc/specification.ttl to what's on the https://www.tdwg.org/standards/itf2/ page, for example. The header metadata is not part of the "official" metadata, so there is no issue of keeping it in synch. However, once one goes down the road of manual editing, you can't really go back to the script again.

The page info is controlled from this file:
https://github.com/tdwg/rs.tdwg.org/blob/master/html/stds-pages/pageInfo.csv
so all that would be involved in "fixing" the problem would be to copy from the relevant abstract into the "summary" column and re-run the script. One does have to take care when editing this particular CSV to not mess up the "other" column since it contains embedded newlines. A good CSV editor like LibreOffice will maintain them faithfully. I'm not sure about a bad editor like Excel, which I do not trust.

What this boils down to is basically a policy decision about how you want to maintain the pages. In AC and DwC, we have been moving away from manual editing as much as possible and switching over to build scripts whenever possible. There are just too many human errors with hand editing. We aren't there yet, but optimally every time a change was made, we would just run a pipeline of build scripts with a single manual edit to a table at the input and no intermediate editing. However, in this case, since the changes to Standards metadata are unlikely to be common, it isn't so much of an issue. The main thing I would anticipate would be changes to the redirect URLs (since we don't control the URLs that point to a lot of the old standards) and the preferred citation formats. That stuff is all generated from here:
https://github.com/tdwg/rs.tdwg.org/blob/master/docs/docs.csv

Steve

**Comment by baskaufs** [comment]
I should add that if the build script for the web pages were to continue to be used, it would make more sense for it to live somewhere in the website repo. The only reason its in the rs.tdwg.org repo is that I have write access to that repo and not to the website repo. If it were to be moved, the file locations here:
https://github.com/tdwg/rs.tdwg.org/blob/21e45d50e2dc031eebc170070ca61367c2cc72c7/html/stds-pages/build.py#L14:L20
would need to be changed to URLs so that they weren't dependent on having a downloaded local copy. 

If that were done, then the generated pages would just go where they belonged in the website repo instead of needing to be manually copied from one folder to another. One would want to create a new branch prior to running the script in order for the changes to be introduced via a pull request since I don't think the rules set up for the website repo allow direct pushes to the master branch. But this is all doable and would just need to be set up initially. After it were set up, one would just need to 
- create a branch
- edit the CSV table
- run the Python script
- create the pull request.

**Pull request merged**
